### ISSUE TITLE
string to html encoding not working

### ISSUE THREAD

**Issue by samthomson** [mitchdenny/ecdc#55] opened 2019-09-10 14:05 UTC
doesn't work for commas, eg `,`

**Comment by mitchdenny** [comment] 2019-11-25 00:42
Do you mean the _String to HTML Entities_ conversion?

**Comment by mitchdenny** [comment] 2020-01-08 11:29
Closing as there has been no follow up.

**Closed by mitchdenny** 2020-01-08 11:29 UTC
Labels: bug, investigating

**Comment by samthomson** [comment] 2020-01-08 14:38
Sorry, can't remember the menu item text and since removed the extension (as it didn't work for me) so can no longer check.
I wanted the html safe version of `,`, welcome to test yourself :+1:

**Comment by mitchdenny** [comment] 2020-01-11 08:18
I close this for now because I think it is behaving correctly (or at least as intended). The intent is to replace characters which aren't valid in HTML. A comma is valid, although there is a HTML entity representation.
